import { Body, Controller, NotFoundException, Post, Res } from "@nestjs/common";
import type { Response } from "express";
import { PrismaService } from "../prisma/prisma.service";
import { QrService } from "../common/qr/qr.service";

// eslint-disable-next-line @typescript-eslint/no-var-requires
const PDFDocument = require("pdfkit");

type CampaignPackBody = {
  campaignId: string;
};

type CampaignRecord = {
  id: string;
  name: string;
  slug?: string | null;
  status?: string | null;
  createdAt?: Date | string | null;
  organization?: {
    id: string;
    name?: string | null;
    slug?: string | null;
  } | null;
};

type RedirectLinkRecord = {
  id: string;
  slug?: string | null;
  title?: string | null;
  destinationUrl?: string | null;
  campaign?: {
    id: string;
    name?: string | null;
  } | null;
};

type NfcTagRecord = {
  id: string;
  uid?: string | null;
  label?: string | null;
  serialNumber?: string | null;
  tagType?: string | null;
  status?: string | null;
  redirectLink?: {
    id?: string | null;
    slug?: string | null;
    title?: string | null;
  } | null;
  store?: {
    id?: string | null;
    name?: string | null;
  } | null;
  campaign?: {
    id?: string | null;
    name?: string | null;
  } | null;
};

@Controller("campaigns")
export class CampaignPackController {
  constructor(
    private readonly prisma: PrismaService,
    private readonly qrService: QrService,
  ) {}

  @Post("export/campaign-pack")
  async exportCampaignPack(@Body() body: CampaignPackBody, @Res() res: Response) {
    const campaignId = body?.campaignId?.trim();

    if (!campaignId) {
      throw new NotFoundException("campaignId is required");
    }

    const campaign = (await this.prisma.campaign.findUnique({
      where: { id: campaignId },
      include: {
        organization: true,
      },
    })) as CampaignRecord | null;

    if (!campaign) {
      throw new NotFoundException("Campaign not found");
    }

    const redirectLinks = (await this.prisma.redirectLink.findMany({
      where: { campaignId },
      orderBy: { createdAt: "desc" },
      take: 12,
    })) as RedirectLinkRecord[];

    const nfcTags = (await this.prisma.nfcTag.findMany({
      where: { campaignId },
      include: {
        redirectLink: true,
        store: true,
        campaign: true,
      },
      orderBy: { createdAt: "desc" },
      take: 12,
    })) as NfcTagRecord[];

    const redirectLinksWithQr = await Promise.all(
      redirectLinks.map(async (item) => {
        const qrValue = this.buildRedirectUrl(item);
        const qr = await this.qrService.generate(qrValue, {
          format: "png",
          size: 700,
          margin: 2,
        });

        return {
          ...item,
          qrValue,
          qrBuffer: qr.payload,
        };
      }),
    );

    const nfcTagsWithQr = await Promise.all(
      nfcTags.map(async (item) => {
        const qrValue = this.buildTapUrl(item);
        const qr = await this.qrService.generate(qrValue, {
          format: "png",
          size: 700,
          margin: 2,
        });

        return {
          ...item,
          qrValue,
          qrBuffer: qr.payload,
        };
      }),
    );

    const doc = new PDFDocument({
      size: "A4",
      margin: 36,
      info: {
        Title: `LUMEVIO Campaign Pack - ${campaign.name}`,
        Author: "LUMEVIO",
        Subject: "Campaign Pack",
      },
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="campaign-pack-${this.safeFileName(campaign.name || campaign.id)}.pdf"`,
    );

    doc.pipe(res);

    this.drawCover(doc, campaign);
    this.drawSummary(doc, campaign, redirectLinksWithQr.length, nfcTagsWithQr.length);
    this.drawRedirectLinks(doc, redirectLinksWithQr);
    this.drawNfcTags(doc, nfcTagsWithQr);

    doc.end();
  }

  private drawCover(doc: typeof PDFDocument.prototype, campaign: CampaignRecord) {
    doc.rect(0, 0, 595, 842).fill("#0B1020");

    doc.fillColor("#6D7CFF").font("Helvetica-Bold").fontSize(12).text("LUMEVIO", 40, 48);

    doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(30).text("Campaign Pack", 40, 110);

    doc.font("Helvetica-Bold").fontSize(24).fillColor("#E5E7EB").text(campaign.name, 40, 160, {
      width: 500,
    });

    doc.font("Helvetica").fontSize(12).fillColor("#A5B4FC")
      .text(`Organization: ${campaign.organization?.name || "-"}`, 40, 220)
      .text(`Slug: ${campaign.slug || "-"}`, 40, 240)
      .text(`Status: ${campaign.status || "-"}`, 40, 260);

    doc.font("Helvetica").fontSize(11).fillColor("#9CA3AF").text(
      "Branded client-facing export generated by LUMEVIO OS.",
      40,
      760,
    );

    doc.addPage();
  }

  private drawSummary(
    doc: typeof PDFDocument.prototype,
    campaign: CampaignRecord,
    redirectCount: number,
    tagCount: number,
  ) {
    this.drawPageHeader(doc, "Campaign Summary");

    doc.font("Helvetica-Bold").fontSize(22).fillColor("#111827").text(campaign.name, 40, 96);

    doc.font("Helvetica").fontSize(11).fillColor("#4B5563")
      .text(`Organization: ${campaign.organization?.name || "-"}`, 40, 136)
      .text(`Campaign slug: ${campaign.slug || "-"}`, 40, 154)
      .text(`Status: ${campaign.status || "-"}`, 40, 172);

    this.drawMetricCard(doc, 40, 230, 160, 92, "Redirect Links", String(redirectCount));
    this.drawMetricCard(doc, 218, 230, 160, 92, "NFC Tags", String(tagCount));
    this.drawMetricCard(doc, 396, 230, 160, 92, "Pack Type", "CLIENT PDF");

    doc.roundedRect(40, 360, 516, 150, 16).fillAndStroke("#F8FAFC", "#E5E7EB");
    doc.font("Helvetica-Bold").fontSize(14).fillColor("#111827").text("What this pack contains", 58, 382);
    doc.font("Helvetica").fontSize(11).fillColor("#374151").text(
      "- Campaign overview\n- Redirect links with QR codes\n- NFC tags with QR/tap references\n- Operational and client-facing export structure",
      58,
      412,
      { width: 470, lineGap: 4 },
    );

    doc.addPage();
  }

  private drawRedirectLinks(
    doc: typeof PDFDocument.prototype,
    items: Array<
      RedirectLinkRecord & {
        qrValue: string;
        qrBuffer: Buffer;
      }
    >,
  ) {
    this.drawPageHeader(doc, "Redirect Links");

    if (items.length === 0) {
      doc.font("Helvetica").fontSize(12).fillColor("#6B7280").text("No redirect links assigned to this campaign.", 40, 100);
      doc.addPage();
      return;
    }

    let y = 96;

    items.forEach((item, index) => {
      if (y + 132 > 790) {
        doc.addPage();
        this.drawPageHeader(doc, "Redirect Links");
        y = 96;
      }

      doc.roundedRect(40, y, 516, 118, 14).fillAndStroke("#FFFFFF", "#E5E7EB");

      doc.font("Helvetica-Bold").fontSize(15).fillColor("#111827").text(
        item.title || item.slug || item.id,
        58,
        y + 16,
        { width: 320 },
      );

      doc.font("Helvetica").fontSize(10).fillColor("#4B5563")
        .text(`Slug: /${item.slug || item.id}`, 58, y + 44)
        .text(`Destination: ${item.destinationUrl || "-"}`, 58, y + 60, { width: 300 })
        .text(`QR URL: ${item.qrValue}`, 58, y + 88, { width: 300 });

      doc.roundedRect(430, y + 14, 96, 96, 10).fillAndStroke("#FFFFFF", "#E5E7EB");
      doc.image(item.qrBuffer, 438, y + 22, { fit: [80, 80] });

      y += 132;
    });

    doc.addPage();
  }

  private drawNfcTags(
    doc: typeof PDFDocument.prototype,
    items: Array<
      NfcTagRecord & {
        qrValue: string;
        qrBuffer: Buffer;
      }
    >,
  ) {
    this.drawPageHeader(doc, "NFC Tags");

    if (items.length === 0) {
      doc.font("Helvetica").fontSize(12).fillColor("#6B7280").text("No NFC tags assigned to this campaign.", 40, 100);
      return;
    }

    let y = 96;

    items.forEach((item) => {
      if (y + 144 > 790) {
        doc.addPage();
        this.drawPageHeader(doc, "NFC Tags");
        y = 96;
      }

      doc.roundedRect(40, y, 516, 128, 14).fillAndStroke("#FFFFFF", "#E5E7EB");

      doc.font("Helvetica-Bold").fontSize(15).fillColor("#111827").text(
        item.label || item.uid || item.id,
        58,
        y + 16,
        { width: 320 },
      );

      doc.font("Helvetica").fontSize(10).fillColor("#4B5563")
        .text(`UID: ${item.uid || "-"}`, 58, y + 44)
        .text(`Store: ${item.store?.name || "-"}`, 58, y + 60)
        .text(`Redirect: ${item.redirectLink?.slug || "-"}`, 58, y + 76)
        .text(`QR URL: ${item.qrValue}`, 58, y + 94, { width: 300 });

      doc.roundedRect(430, y + 16, 96, 96, 10).fillAndStroke("#FFFFFF", "#E5E7EB");
      doc.image(item.qrBuffer, 438, y + 24, { fit: [80, 80] });

      y += 142;
    });
  }

  private drawPageHeader(doc: typeof PDFDocument.prototype, title: string) {
    doc.font("Helvetica-Bold").fontSize(10).fillColor("#4F46E5").text("LUMEVIO", 40, 32);
    doc.font("Helvetica-Bold").fontSize(22).fillColor("#111827").text(title, 40, 52);
    doc.moveTo(40, 80).lineTo(556, 80).strokeColor("#E5E7EB").lineWidth(1).stroke();
  }

  private drawMetricCard(
    doc: typeof PDFDocument.prototype,
    x: number,
    y: number,
    w: number,
    h: number,
    label: string,
    value: string,
  ) {
    doc.roundedRect(x, y, w, h, 14).fillAndStroke("#FFFFFF", "#E5E7EB");
    doc.font("Helvetica").fontSize(10).fillColor("#6B7280").text(label, x + 18, y + 18);
    doc.font("Helvetica-Bold").fontSize(24).fillColor("#111827").text(value, x + 18, y + 40);
  }

  private buildRedirectUrl(link: RedirectLinkRecord) {
    const publicBaseUrl =
      process.env.PUBLIC_GO_BASE_URL?.trim() ||
      process.env.PUBLIC_APP_BASE_URL?.trim() ||
      "http://localhost:3001";

    if (link.slug) {
      return `${publicBaseUrl.replace(/\/+$/, "")}/r/${encodeURIComponent(link.slug)}`;
    }

    return link.destinationUrl || `${publicBaseUrl.replace(/\/+$/, "")}/r/${link.id}`;
  }

  private buildTapUrl(tag: NfcTagRecord) {
    const publicBaseUrl =
      process.env.PUBLIC_GO_BASE_URL?.trim() ||
      process.env.PUBLIC_APP_BASE_URL?.trim() ||
      "http://localhost:3001";

    if (tag.redirectLink?.slug) {
      return `${publicBaseUrl.replace(/\/+$/, "")}/r/${encodeURIComponent(
        tag.redirectLink.slug,
      )}?nfc_tag_id=${encodeURIComponent(tag.id)}`;
    }

    return `${publicBaseUrl.replace(/\/+$/, "")}/tap/${encodeURIComponent(tag.id)}`;
  }

  private safeFileName(value?: string | null) {
    if (!value) return "campaign-pack";
    return value
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9-_]+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
  }
}